// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoheG9HtiCwSwlndTihRQvc10eNbqGaY8',
    appId: '1:981743629235:web:8d00152418bcc40de8d1c6',
    messagingSenderId: '981743629235',
    projectId: 'rsl-shard-memory-kretuno',
    authDomain: 'rsl-shard-memory-kretuno.firebaseapp.com',
    storageBucket: 'rsl-shard-memory-kretuno.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCykFUloz9DNxncAhp95ubDUBq_chhQj8A',
    appId: '1:981743629235:android:d89aa8f973e2f54de8d1c6',
    messagingSenderId: '981743629235',
    projectId: 'rsl-shard-memory-kretuno',
    storageBucket: 'rsl-shard-memory-kretuno.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDO8U9oopuYpGnxHNoVufrLlkV_iWeyg',
    appId: '1:981743629235:ios:530d5391771402b7e8d1c6',
    messagingSenderId: '981743629235',
    projectId: 'rsl-shard-memory-kretuno',
    storageBucket: 'rsl-shard-memory-kretuno.firebasestorage.app',
    iosBundleId: 'com.local.raidShardCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCDO8U9oopuYpGnxHNoVufrLlkV_iWeyg',
    appId: '1:981743629235:ios:530d5391771402b7e8d1c6',
    messagingSenderId: '981743629235',
    projectId: 'rsl-shard-memory-kretuno',
    storageBucket: 'rsl-shard-memory-kretuno.firebasestorage.app',
    iosBundleId: 'com.local.raidShardCounter',
  );
}
